// <auto-generated />
using System;
using Forum.App.Data;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.App.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20240124143854_CreateAndSeedDb")]
    partial class CreateAndSeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forum.App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6d99310-8a2c-42ab-8cf5-a07ce17c232b"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ullamcorper, risus quis fermentum lacinia, dui nisi posuere nisl, eget dictum.",
                            Title = "My First Post"
                        },
                        new
                        {
                            Id = new Guid("cfdcbea5-1be9-4cb6-8e18-2d3a14d467cb"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu lacinia turpis. Quisque eu dapibus sem. Mauris pharetra ultrices leo.",
                            Title = "My Second Post"
                        },
                        new
                        {
                            Id = new Guid("63277475-01c3-4dc1-84da-5a51ebac7de9"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lacinia nibh a risus hendrerit tincidunt. Donec porta nulla arcu, at.",
                            Title = "My Third Post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
