CREATE DATABASE [Minions2023]

USE [Minions2023]

GO

CREATE TABLE[Minions](
     [Id] INT PRIMARY KEY, --PRIMARY KEY MAKES IT NOT NULL
	 [Name] NVARCHAR(50) NOT NULL,
	 [Age] INT NOT NULL
)

GO

CREATE TABLE [Towns](
     [Id] INT PRIMARY KEY,
	 [Name] NVARCHAR(70) NOT NULL,
)

ALTER TABLE [Minions]
ADD [TownId] INT FOREIGN KEY REFERENCES [Towns]([Id]) NOT NULL 